// <auto-generated />
namespace DailyEntry.Infrastructure.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UpdataDairyTableNameToDaily : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdataDairyTableNameToDaily));
        
        string IMigrationMetadata.Id
        {
            get { return "201709101311580_UpdataDairyTableNameToDaily"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
